name: prod-deploy
on:
  push:
    branches:
      - main
jobs:
  invoke-prod-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "deploy"
        run: |
          curl --fail --silent --show-error -X POST \
              -H "Authorization: Bearer ${{ secrets.CI_TOKEN }}" \
              -H "Content-Type:application/json" \
              -d '{"steps": ["deploy_auth", "deploy_batch", "deploy_ci", "deploy_notebook", "deploy_query", "deploy_router"], "sha": "${{ github.sha }}"}' \
              https://ci.hail.populationgenomics.org.au/api/v1alpha/prod_deploy
